console.log(1, 'foo', true, {});
console.debug(1, 'foo', true, {});
console.info(1, 'foo', true, {});
console.warn(1, 'foo', true, {});
console.error(1, 'foo', true, {});
console.group(1, 'foo', true, {});
console.groupEnd();
console.assert(true, 'foo', true, {});
console.assert(false, 'foo', true, {});
console.count();
console.count('foo');
console.countReset();
console.trace();
console.dirxml({});
